### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by jpfeiffer16** [aaronjanse/asciidots-demo-backend#1]
Hi
I'm trying to get this setup on my local so maybe I can help with [This issue](https://github.com/aaronduino/asciidots/issues/13)
What do I have to do to setup the requirements in requirements.txt?

**Comment by aaronjanse** [comment]
First, thanks for helping!
Seriously, I really appreciate it.

### Running the backend
You'd install the requirements in requirements.txt with:

```
pip3 install -r requirements.txt
```

Once you do that, you can run the server via:

```
python3 app.py
```

Unless you set the `PORT` environment variable, this will run on port `5000`.

### Running the frontend
Clone the [frontend repo](https://github.com/aaronduino/asciidots-static-server).

Change [the lines where the web socket URL is defined](https://github.com/aaronduino/asciidots-static-server/blob/056f1f2e4f38eaa6d0f08d08c1c0b914cc88758e/index.html#L143-L144) to point to localhost. (Change this back before you make a PR)

After that, you can serve that file on localhost with:

```
python3 -m http.server
```

You can now view the frontend at [localhost:8000](http://localhost:8000)

Once again, thanks for helping

**Comment by jpfeiffer16** [comment]
Cool, thanks. I'll walk through the steps. No problem, I figure it's a good way to learn some more python and do some JS.

**Comment by aaronjanse** [comment]
@jpfeiffer16, I think the dropped char problem might have to do with the JS (client-side) parsing.
The way its done is... [questionable](https://github.com/aaronduino/asciidots-static-server/blob/056f1f2e4f38eaa6d0f08d08c1c0b914cc88758e/index.html#L170-L185)

**Comment by jpfeiffer16** [comment]
Ok. I'll start there. Thanks
